using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

		//=============================================================
		//||                   Generated by BansheeGz Code Generator ||
		//=============================================================

		public partial class TBL_MOVE_CARD : BGEntity
		{

			//=============================================================
			//||                   Generated by BansheeGz Code Generator ||
			//=============================================================

			public class Factory : BGEntity.EntityFactory
			{
				public BGEntity NewEntity(BGMetaEntity meta)
				{
					return new TBL_MOVE_CARD(meta);
				}
				public BGEntity NewEntity(BGMetaEntity meta, BGId id)
				{
					return new TBL_MOVE_CARD(meta, id);
				}
			}
			private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
			public static BansheeGz.BGDatabase.BGMetaRow MetaDefault
			{
				get
				{
					if(_metaDefault==null || _metaDefault.IsDeleted) _metaDefault=BGRepo.I.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(4871748722261721329,2890707906641499285));
					return _metaDefault;
				}
			}
			public static BansheeGz.BGDatabase.BGRepoEvents Events
			{
				get
				{
					return BGRepo.I.Events;
				}
			}
			private static readonly List<BGEntity> _find_Entities_Result = new List<BGEntity>();
			public static int CountEntities
			{
				get
				{
					return MetaDefault.CountEntities;
				}
			}
			public System.String name
			{
				get
				{
					return _name[Index];
				}
				set
				{
					_name[Index] = value;
				}
			}
			public System.Int32 Distance
			{
				get
				{
					return _Distance[Index];
				}
				set
				{
					_Distance[Index] = value;
				}
			}
			public System.String Comment
			{
				get
				{
					return _Comment[Index];
				}
				set
				{
					_Comment[Index] = value;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
			public static BansheeGz.BGDatabase.BGFieldEntityName _name
			{
				get
				{
					if(_ufle12jhs77_name==null || _ufle12jhs77_name.IsDeleted) _ufle12jhs77_name=(BansheeGz.BGDatabase.BGFieldEntityName) MetaDefault.GetField(new BGId(5120574290386162048,7495979722686343337));
					return _ufle12jhs77_name;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Distance;
			public static BansheeGz.BGDatabase.BGFieldInt _Distance
			{
				get
				{
					if(_ufle12jhs77_Distance==null || _ufle12jhs77_Distance.IsDeleted) _ufle12jhs77_Distance=(BansheeGz.BGDatabase.BGFieldInt) MetaDefault.GetField(new BGId(4635682263990587347,12589798964238248124));
					return _ufle12jhs77_Distance;
				}
			}
			private static BansheeGz.BGDatabase.BGFieldString _ufle12jhs77_Comment;
			public static BansheeGz.BGDatabase.BGFieldString _Comment
			{
				get
				{
					if(_ufle12jhs77_Comment==null || _ufle12jhs77_Comment.IsDeleted) _ufle12jhs77_Comment=(BansheeGz.BGDatabase.BGFieldString) MetaDefault.GetField(new BGId(5211601573426285838,9146758092986032047));
					return _ufle12jhs77_Comment;
				}
			}
			private static readonly TBL_MOVE_CARD.Factory _factory0_PFS = new TBL_MOVE_CARD.Factory();
			public TBL_MOVE_CARD() : base(MetaDefault)
			{
			}
			public TBL_MOVE_CARD(BGId id) : base(MetaDefault, id)
			{
			}
			public TBL_MOVE_CARD(BGMetaEntity meta) : base(meta)
			{
			}
			public TBL_MOVE_CARD(BGMetaEntity meta, BGId id) : base(meta, id)
			{
			}
			public static TBL_MOVE_CARD FindEntity(Predicate<TBL_MOVE_CARD> filter)
			{
				return MetaDefault.FindEntity(entity => filter==null || filter((TBL_MOVE_CARD) entity)) as TBL_MOVE_CARD;
			}
			public static List<TBL_MOVE_CARD> FindEntities(Predicate<TBL_MOVE_CARD> filter, List<TBL_MOVE_CARD> result=null, Comparison<TBL_MOVE_CARD> sort=null)
			{
				result = result ?? new List<TBL_MOVE_CARD>();
				_find_Entities_Result.Clear();
				MetaDefault.FindEntities(filter == null ? (Predicate<BGEntity>) null: e => filter((TBL_MOVE_CARD) e), _find_Entities_Result, sort == null ? (Comparison<BGEntity>) null : (e1, e2) => sort((TBL_MOVE_CARD) e1, (TBL_MOVE_CARD) e2));
				if (_find_Entities_Result.Count != 0)
				{
					for (var i = 0; i < _find_Entities_Result.Count; i++) result.Add((TBL_MOVE_CARD) _find_Entities_Result[i]);
					_find_Entities_Result.Clear();
				}
				return result;
			}
			public static void ForEachEntity(Action<TBL_MOVE_CARD> action, Predicate<TBL_MOVE_CARD> filter=null, Comparison<TBL_MOVE_CARD> sort=null)
			{
				MetaDefault.ForEachEntity(entity => action((TBL_MOVE_CARD) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((TBL_MOVE_CARD) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((TBL_MOVE_CARD)e1,(TBL_MOVE_CARD)e2));
			}
			public static TBL_MOVE_CARD GetEntity(BGId entityId)
			{
				return (TBL_MOVE_CARD) MetaDefault.GetEntity(entityId);
			}
			public static TBL_MOVE_CARD GetEntity(int index)
			{
				return (TBL_MOVE_CARD) MetaDefault[index];
			}
			public static TBL_MOVE_CARD GetEntity(string entityName)
			{
				return (TBL_MOVE_CARD) MetaDefault.GetEntity(entityName);
			}
			public static TBL_MOVE_CARD NewEntity()
			{
				return (TBL_MOVE_CARD) MetaDefault.NewEntity();
			}
		}

#pragma warning restore 414
